name: any_animated_button
description: Button, which animates between idle, progress and success/error state, indicating that some process is running in the background.
version: 0.0.5
homepage: https://appvinio.com/
repository: https://github.com/appvinio/any_animated_button
issue_tracker: https://github.com/appvinio/any_animated_button/issues

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0
  dartz: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
